// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC80GAdQJGx0ZesmN6ihDRrgTChzN-dbKw',
    appId: '1:1098894563083:web:0aeb9a4e5f451dcb50b40e',
    messagingSenderId: '1098894563083',
    projectId: 'tes-iot-7ad23',
    authDomain: 'tes-iot-7ad23.firebaseapp.com',
    databaseURL: 'https://tes-iot-7ad23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-iot-7ad23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJ2W2PwQ3XhAeArPk6WcoYS88KNk2oDY',
    appId: '1:1098894563083:android:6179393b1d80eccd50b40e',
    messagingSenderId: '1098894563083',
    projectId: 'tes-iot-7ad23',
    databaseURL: 'https://tes-iot-7ad23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-iot-7ad23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-0SfVF297XCW7LkArc0Nrff48v8C-cA',
    appId: '1:1098894563083:ios:c73de9787686cac550b40e',
    messagingSenderId: '1098894563083',
    projectId: 'tes-iot-7ad23',
    databaseURL: 'https://tes-iot-7ad23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-iot-7ad23.firebasestorage.app',
    iosBundleId: 'com.example.iotLockerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-0SfVF297XCW7LkArc0Nrff48v8C-cA',
    appId: '1:1098894563083:ios:c73de9787686cac550b40e',
    messagingSenderId: '1098894563083',
    projectId: 'tes-iot-7ad23',
    databaseURL: 'https://tes-iot-7ad23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-iot-7ad23.firebasestorage.app',
    iosBundleId: 'com.example.iotLockerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC80GAdQJGx0ZesmN6ihDRrgTChzN-dbKw',
    appId: '1:1098894563083:web:4d55cf4ef09f6f4e50b40e',
    messagingSenderId: '1098894563083',
    projectId: 'tes-iot-7ad23',
    authDomain: 'tes-iot-7ad23.firebaseapp.com',
    databaseURL: 'https://tes-iot-7ad23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tes-iot-7ad23.firebasestorage.app',
  );
}
